#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("function_test_1.Resource", IsApplication=true)]

namespace function_test_1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000d
			public const int addition = 2131034125;
			
			// aapt resource value: 0x7f050001
			public const int answer = 2131034113;
			
			// aapt resource value: 0x7f050018
			public const int answerButton = 2131034136;
			
			// aapt resource value: 0x7f050016
			public const int clear = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int clearall = 2131034135;
			
			// aapt resource value: 0x7f050010
			public const int division = 2131034128;
			
			// aapt resource value: 0x7f050009
			public const int eight = 2131034121;
			
			// aapt resource value: 0x7f050006
			public const int five = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int four = 2131034117;
			
			// aapt resource value: 0x7f050014
			public const int infix = 2131034132;
			
			// aapt resource value: 0x7f050000
			public const int label = 2131034112;
			
			// aapt resource value: 0x7f050012
			public const int modulo = 2131034130;
			
			// aapt resource value: 0x7f05000f
			public const int multiplication = 2131034127;
			
			// aapt resource value: 0x7f05000a
			public const int nine = 2131034122;
			
			// aapt resource value: 0x7f050002
			public const int one = 2131034114;
			
			// aapt resource value: 0x7f05000c
			public const int point = 2131034124;
			
			// aapt resource value: 0x7f050015
			public const int postfix = 2131034133;
			
			// aapt resource value: 0x7f050011
			public const int power = 2131034129;
			
			// aapt resource value: 0x7f050008
			public const int seven = 2131034120;
			
			// aapt resource value: 0x7f050013
			public const int sin = 2131034131;
			
			// aapt resource value: 0x7f050007
			public const int six = 2131034119;
			
			// aapt resource value: 0x7f05000e
			public const int subtraction = 2131034126;
			
			// aapt resource value: 0x7f050004
			public const int three = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int two = 2131034115;
			
			// aapt resource value: 0x7f05000b
			public const int zero = 2131034123;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
